/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.FenetreVictoire to edit this template
 */
package lightoff_druon_version_console;

/**
 *
 * @author vdruo
 */
public class FenetreVictoire extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public FenetreVictoire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBoutonVictoire = new javax.swing.JPanel();
        TexteVictoire = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBoutonVictoire.setBackground(new java.awt.Color(255, 255, 255));

        TexteVictoire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TexteVictoire.setText("Bravo, vous avez gagné !");
        TexteVictoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexteVictoireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBoutonVictoireLayout = new javax.swing.GroupLayout(PanelBoutonVictoire);
        PanelBoutonVictoire.setLayout(PanelBoutonVictoireLayout);
        PanelBoutonVictoireLayout.setHorizontalGroup(
            PanelBoutonVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBoutonVictoireLayout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(TexteVictoire, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );
        PanelBoutonVictoireLayout.setVerticalGroup(
            PanelBoutonVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoutonVictoireLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(TexteVictoire, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBoutonVictoire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBoutonVictoire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TexteVictoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexteVictoireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexteVictoireActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBoutonVictoire;
    private javax.swing.JTextField TexteVictoire;
    // End of variables declaration//GEN-END:variables
}
