/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_druon_version_console;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author vdruo
 */
public class FenetreDebutPartie extends javax.swing.JFrame {

    int diff;
    int nbLignes;
    
    /**
     * Creates new form FenetreDebutPartie
     */
    public FenetreDebutPartie() {
        initComponents();
    }
    
    public int ChoixDiff() {
        
        JButton BoutonNormal = new JButton("Normal");
        JButton BoutonDificile = new JButton("Difficile");
        JButton BoutonCauchemard = new JButton("Cauchemard");
        
        ActionListener ecouteurClick = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                  diff = 0;
                }
        };
        BoutonNormal.addActionListener(ecouteurClick); 
        
    
        ActionListener ecouteurClick1 = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                  diff = 1;
                }
        };
        BoutonDificile.addActionListener(ecouteurClick1);
    
        
        ActionListener ecouteurClick2 = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                  diff = 2;
                }
            };
        BoutonCauchemard.addActionListener(ecouteurClick2);
    
     
    JOptionPane.showMessageDialog(null, new Object[]{BoutonNormal, BoutonDificile, BoutonCauchemard},
                "Choisissez la difficulté", JOptionPane.PLAIN_MESSAGE);    
        
    return diff;
    
    
    }

  public int nbLignes() {
        // Demander à l'utilisateur d'entrer le nombre de lignes
        String input = JOptionPane.showInputDialog("Entrez le nombre de lignes :");

        // Gérer le cas où l'utilisateur annule ou entre une valeur non numérique
        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            // Gérer l'exception, par exemple en utilisant une valeur par défaut
            JOptionPane.showMessageDialog(null, "Veuillez entrer un nombre valide. Utilisation de la valeur par défaut (0).");
            return 0;
        }
    }  
  
  
  public int nbColonnes() {
        // Demander à l'utilisateur d'entrer le nombre de colonne
        String input = JOptionPane.showInputDialog("Entrez le nombre de colonnes :");

        // Gérer le cas où l'utilisateur annule ou entre une valeur non numérique
        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            // Gérer l'exception, par exemple en utilisant une valeur par défaut
            JOptionPane.showMessageDialog(null, "Veuillez entrer un nombre valide. Utilisation de la valeur par défaut (0).");
            return 0;
        }
    } 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInit = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelInit.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setText("          Bienvenu dans LightOff !");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(255, 255, 153));
        jTextField3.setText("Normal (2 couleurs)       Difficile (3 couleurs)       Cauchemard (4 couleurs)");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 255, 153));
        jTextField2.setText("                                     3 niveaux de difficulté :");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(255, 204, 255));
        jTextField4.setText("          Choisisez le nombre de lignes et de colonnes que vous voulez");

        jTextField5.setBackground(new java.awt.Color(255, 204, 255));
        jTextField5.setText("     Cela générera une grille avec tout ce que vous avez choisi ! Enjoy");

        javax.swing.GroupLayout PanelInitLayout = new javax.swing.GroupLayout(PanelInit);
        PanelInit.setLayout(PanelInitLayout);
        PanelInitLayout.setHorizontalGroup(
            PanelInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInitLayout.createSequentialGroup()
                .addGroup(PanelInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInitLayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInitLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        PanelInitLayout.setVerticalGroup(
            PanelInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInitLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDebutPartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDebutPartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDebutPartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDebutPartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDebutPartie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInit;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
